webserver:
  port: "8080"
  ip: "127.0.0.1"
  scheme: "http"  # http or https
  base_url: ""  # Public URL for short links (e.g., "http://localhost:80" or "https://myapp.com"). Leave empty to auto-construct from scheme, ip, and port
  read_timeout: 15  # seconds
  write_timeout: 15  # seconds
  shutdown_timeout: 30  # seconds

redis:
  address: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  operation_timeout: 5  # seconds for individual operations

cache:
  enabled: true          # Enable in-memory cache for hot URLs
  max_size_mb: 100       # Maximum cache size in megabytes
  ttl_seconds: 300       # Cache TTL (5 minutes)
  counter_size: 1000000  # Number of keys to track for admission policy

ratelimit:
  requests_per_second: 10
  burst: 20

features:
  deduplication_enabled: true  # Check for duplicate original URLs and return existing short URL
