webserver:
  port: "8080"
  ip: "127.0.0.1"
  scheme: "http"  # http or https
  base_url: ""  # Public URL for short links (e.g., "http://localhost:80" or "https://myapp.com"). Leave empty to auto-construct from scheme, ip, and port
  read_timeout: 15  # seconds
  write_timeout: 15  # seconds
  shutdown_timeout: 30  # seconds

redis:
  address: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  operation_timeout: 5  # seconds for individual operations

cache:
  enabled: true          # Enable in-memory cache for hot URLs
  max_size_mb: 100       # Maximum cache size in megabytes
  ttl_seconds: 300       # Cache TTL (5 minutes)
  counter_size: 1000000  # Number of keys to track for admission policy

ratelimit:
  requests_per_second: 10
  burst: 20

features:
  deduplication_enabled: true  # Check for duplicate original URLs and return existing short URL
  custom_slugs_enabled: true   # Allow users to specify custom slugs (vanity URLs)
  min_slug_length: 3          # Minimum length for custom slugs
  max_slug_length: 64         # Maximum length for custom slugs
  require_auth_for_custom: false  # Future: require API authentication for custom slugs
  slug_suggestions_count: 3   # Number of alternative slug suggestions to provide on conflict
  preview_enabled: true       # Enable URL preview page (anti-phishing protection)
  preview_auto_redirect: 0    # Auto-redirect after N seconds (0 = disabled)

security:
  url_scanning_enabled: true   # Enable malware/phishing URL scanning
  blocklist_enabled: true      # Enable local blocklist
  safe_browsing_api_key: ""    # Google Safe Browsing API key (optional, leave empty to use blocklist only)
  bot_detection_enabled: true  # Enable bot detection
  bot_max_requests_per_minute: 60  # Max requests per minute per IP before flagging as bot

admin:
  enabled: true                     # Enable admin dashboard and API
  api_key: "your-secret-admin-key"  # Admin API key - CHANGE THIS IN PRODUCTION!

# Email configuration (for OTP and notifications)
email:
  enabled: false  # Set to true in production
  smtp_host: "smtp.gmail.com"
  smtp_port: "587"
  smtp_username: "your-email@gmail.com"
  smtp_password: "your-app-password"  # Use app-specific password for Gmail
  from_email: "noreply@yourdomain.com"
  from_name: "Short URL Generator"

# JWT authentication
jwt:
  secret_key: "your-very-long-secret-jwt-key-change-this-in-production-min-32-chars"  # CHANGE IN PRODUCTION! Minimum 32 characters
  access_token_duration: "15m"   # Access token validity (e.g., 15m, 1h, 24h)
  refresh_token_duration: "168h" # Refresh token validity (168h = 7 days)
  otp_duration: "10m"            # OTP code validity (10 minutes)

# User features
user_features:
  registration_enabled: true           # Allow new user registration
  custom_domains_enabled: true         # Allow users to use custom domains
  password_protected_urls_enabled: true # Allow password-protected URLs
  scheduled_urls_enabled: true         # Allow scheduled activation/deactivation
  url_aliases_enabled: true            # Allow multiple short codes for same URL
  max_urls_per_user: 1000              # Maximum URLs per user (0 = unlimited)
  max_aliases_per_url: 10              # Maximum aliases per URL
